spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTImezone=true&serverTimezone=UTC
      username: root
      password: Godblessyou_forever1@#
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
     
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    
    
    